[package]
name = "rc2"
version = "0.3.0"
description = "RC2 block cipher"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/rc2"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "rc2", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher = "= 0.7.0-pre"
opaque-debug = "0.2"

[dev-dependencies]
block-cipher = { version = "0.7.0-pre", features = ["dev"] }
