[package]
name = "magma"
version = "0.1.1"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "Magma (GOST 28147-89 and GOST R 34.12-2015) block cipher"
documentation = "https://docs.rs/magma"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "magma", "gost", "block-cipher"]

[dependencies]
generic-array = "0.6"
byte-tools = "0.1"
block-cipher-trait = "0.3"

[dev-dependencies]
crypto-tests = "0.3"
