[package]
name = "blowfish"
version = "0.4.0"
description = "Blowfish block cipher"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/blowfish"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "blowfish", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher = "= 0.7.0-pre"
byteorder = { version = "1", default-features = false }
opaque-debug = "0.2"

[dev-dependencies]
block-cipher = { version = "= 0.7.0-pre", features = ["dev"] }

[features]
bcrypt = []

[badges]
travis-ci = { repository = "RustCrypto/block-ciphers" }
