language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: nightly
      script: cd aesni && cargo test --verbose
  allow_failures:
    - rust: nightly
script:
    - cargo test --verbose --all
