[workspace]
members = [
    "aes",
    "blowfish",
    "block-modes",
    "cast5",
    "des",
    "idea",
    "kuznyechik",
    "magma",
    "rc2",
    "serpent",
    "sm4",
    "twofish",
    "threefish",
]

[patch.crates-io]
block-cipher = { git = "https://github.com/RustCrypto/traits.git" }
stream-cipher = { git = "https://github.com/RustCrypto/traits.git" }
