[workspace]
members = [
    "aes",
    "blowfish",
    "block-modes",
    "cast5",
    "des",
    "idea",
    "kuznyechik",
    "magma",
    "rc2",
    "serpent",
    "sm4",
    "twofish",
    "threefish",
]
