[workspace]
members = [
    "blowfish",
    #"block-modes",
    "des",
    "kuznyechik",
    "magma",
    "rc2",
    "twofish"
]

[patch.crates-io]
block-cipher-trait = { git = "https://github.com/RustCrypto/traits", branch="new_versiion" }
