[package]
name = "twofish"
version = "0.2.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "Twofish block cipher"
documentation = "https://docs.rs/twofish"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "twofish", "block-cipher"]

[dependencies]
generic-array = "0.8"
byte-tools = "0.2"
block-cipher-trait = "0.4.0-gamma"

[dev-dependencies]
crypto-tests = "^0.5.4"
