[package]
name = "twofish"
version = "0.2.0"
description = "Twofish block cipher"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/twofish"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "twofish", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
byteorder = { version = "1", default-features = false }
block-cipher-trait = "0.6"
opaque-debug = "0.2"

[dev-dependencies]
block-cipher-trait = { version = "0.6", features = ["dev"] }
